### ISSUE TITLE
printPerson

### ISSUE THREAD

**Issue by Foryah** [eliseonuta/Agenda#2]
I noticed in the code you do this in 3 places : 
```
        cout << "Entry #" << x << "\n";
        cout << "Name: " << p->name << "\n";
        cout << "Phone Number: " << p->phoneNumber << "\n";
        cout << "Address: " << p->address << "\n\n";
        cout << endl;
```

This can be extracted in a function `printPerson` which receives a `Person` as an argument `Person *p` and then the exact same code as above is executed. Then the function can be called in all places where you need to display a person information :)

**Comment by eliseinuta** [comment]
done :)
